config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/articles", to: "articles#index"
  get "/articles/new", to: "articles#new"
  get "articles/:id", to: "articles#show", as: :article

  post "/articles", to: "articles#create"

  get "/articles/:id/edit", to:"articles#edit", as: :edit_article
  patch "/articles/:id", to: "articles#update"
  delete "/articles/:id", to: "articles#destroy", as: :destroy_article

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    redirect_to articles_path
  end

  def destroy
    @article= Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1 style="font-size:20px; color:green">Edit</h1>

<%= form_with model: @article do |a| %>
  <%= a.label :title %>
  <%= a.text_field :title %>
  <%= a.label :content %>
  <%= a.text_field :content %>
  <%= a.submit %>
<% end %>

<%= link_to "See Articles", articles_path%>

app/views/articles/index.html.erb
<h1 style="display:flex; justify-content:center; text-align:center">Space Articles</h1>
<ul style="list-style-type: none; color:blue, display:flex; justify-content:center; text-align:center">
  <%@articles.each do|article|%>
    <li style="color: blue"> <%= article.title %> <%style="text-decoration: none"%> </li>
  <% end %>
</ul>

<%= link_to "Add a new article", articles_new_path %>

app/views/articles/new.html.erb
<h1 style="font-size:20px; color:green">create your Article</h1>

<%= form_with model: @article do |a| %>
  <%= a.label :title %>
  <%= a.text_field :title %>
  <%= a.label :content %>
  <%= a.text_field :content %>
  <%= a.submit %>
<% end %>

app/views/articles/show.html.erb
<h1 style="color:red; font-size:25px; display:flex; justify-content:center; text-align:center"> <%= @article.title %></h1>
<%= link_to "Edit", edit_article_path(@article.id) %>
<%= link_to "Back to list", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>